allow passing handlers to routes
dymmond/esmerald pull request #429
Opened 2024-11-07 19:46 UTC by devkral

### Checklist

- [x] The code has 1000% test coverage.
- [x] The documentation was properly created or updated (if applicable) following the correct guidelines and appropriate language.
- [x] I branched out from the latest main or is a sub-branch.

### Summary or description

Changes:
- simplify routing by allowing just passing HTTP/Websocket Handlers to routes
  This matches the add_route behavior.

2024-11-08 07:22 UTC, tarsil commented
Still missing a lot of things:

1. OpenAPI tests.
2. Tests where you can add also in the include.
3. The update of the documentation in the routing section where it's detailed explained this additional way.

2024-11-08 09:59 UTC, devkral commented
done. I hope the little remark is enough.

2024-11-08 16:08 UTC, tarsil requested changes

2024-11-08 16:08 UTC, tarsil commented on docs/en/docs/release-notes.md
> +- Allow passing HTTP/WebSocket handlers directly to routes. They are automatically wrapped in Gateways-
`- Allow passing HTTP/WebSocket handlers directly to routes as alternative to defining a Gateway/WebsocketGateway.`

2024-11-08 16:08 UTC, tarsil commented on docs/en/docs/routing/routes.md
> +It is automatically added when just passing an HTTP/Websocket handler to routes.
`When a handler is passed instead of a Gateway/WebsocketGateway, it will be automatically mapped to the corresponding wrapper and added to the routes.`

2024-11-08 16:08 UTC, tarsil commented on docs/en/docs/routing/routes.md
> +This allows overwriting options of the handler route specific.
`This allows overwriting options of the specific handler route.`

2024-11-08 16:08 UTC, tarsil commented on docs/en/docs/routing/routes.md
> +This allows overwriting options of the WebsocketHandler route specific.
`This allows overwriting options of the specific WebsocketHandler route.`

2024-11-08 16:08 UTC, tarsil commented on esmerald/routing/router.py
> +                pass
```
if isinstance(route, WebhookHandler): ...
```

Use the elipsis here, its cleaner. Off as the linter should have done that for you.

2024-11-08 16:08 UTC, tarsil commented on esmerald/routing/router.py
> +        if isinstance(value, (Include, Gateway, WebSocketGateway, WebhookGateway)):
Repeated words. Nice catch

2024-11-08 16:08 UTC, tarsil commented on esmerald/routing/router.py
> +                pass
Same as the router. Ellipsis  `...` instead of the pass

2024-11-08 16:09 UTC, tarsil commented
@devkral this looks good, simple and yet effective addition. The comments are more docs than anything else. The rest looks good

2024-11-09 02:22 UTC, devkral commented on esmerald/routing/router.py
> +                pass
when all are merged, we should reformat with hatch fmt and use this as linter.

2024-11-09 10:18 UTC, tarsil requested changes

2024-11-09 10:18 UTC, tarsil commented on esmerald/routing/router.py
> +                # if using add_websocket_route, we would enter a completely different code path with a not fully initialized router
Why a comment here? Needs to be removed

2024-11-09 10:33 UTC, tarsil commented on esmerald/routing/router.py
> +        # copy routes shallow, fixes bug with tests/dependencies/test_http_handler_dependency_injection.py
No need for this

2024-11-09 11:58 UTC, merged